In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
 !pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 31.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 44.7 MB/s eta 0:00:00


In [ ]:
import sklearn
import tensorflow as tf
from transformers import TFDistilBertForSequenceClassification, TFTrainer, TFTrainingArguments
from transformers import DistilBertTokenizerFast
from sklearn.model_selection import train_test_split

In [ ]:
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Emotion Recognition/Dataset/tweets.csv')

df

Unnamed: 0  sentiment  \
0               0    sadness   
1               1    sadness   
2               2    neutral   
3               3    sadness   
4               4    sadness   
...           ...        ...   
21241       21241    neutral   
21242       21242    neutral   
21243       21243    neutral   
21244       21244  happiness   
21245       21245  happiness   

                                                 content  Text_length  label  
0      layin n bed with a headache  ughhhh   waitin o...           60      2  
1                    funeral ceremony   gloomy friday              35      2  
2       we want to trade with someone who has houston...           72      0  
3      i should be sleep  but im not  thinking about ...          132      2  
4                           charlene my love  i miss you           29      2  
...                                                  ...          ...    ...  
21241   can you give me the link for the kimba diarie...           55      0  
21242   ooo showing of your french skills   lol thing...          110      0  
21243   haha  yeah  twitter has many uses  for me it ...           96      0  
21244                      succesfully following tayla             29      1  
21245   wassup beautiful    follow me    peep out my ...          113      1  

[21246 rows x 5 columns]

In [ ]:
df['label'].value_counts()

0    8579
1    5208
2    5162
4    2187
3     110
Name: label, dtype: int64

In [ ]:
X_train = train_df['text'].tolist()
y_train = train_df['label'].tolist()
# y_train

[0,
 2,
 2,
 2,
 2,
 4,
 1,
 1,
 4,
 1,
 0,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 5,
 2,
 4,
 2,
 1,
 4,
 0,
 1,
 0,
 0,
 0,
 2,
 5,
 2,
 1,
 1,
 4,
 2,
 1,
 1,
 0,
 4,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 3,
 1,
 0,
 1,
 2,
 5,
 5,
 2,
 1,
 2,
 1,
 1,
 1,
 5,
 1,
 1,
 2,
 1,
 1,
 5,
 1,
 4,
 1,
 2,
 4,
 4,
 1,
 0,
 0,
 4,
 2,
 3,
 3,
 4,
 3,
 0,
 0,
 1,
 2,
 0,
 2,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 0,
 0,
 1,
 1,
 4,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 4,
 0,
 1,
 1,
 2,
 5,
 2,
 0,
 2,
 0,
 3,
 0,
 0,
 4,
 1,
 2,
 4,
 2,
 2,
 1,
 1,
 1,
 5,
 4,
 2,
 1,
 0,
 1,
 2,
 1,
 5,
 0,
 1,
 3,
 2,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 5,
 5,
 1,
 0,
 0,
 1,
 2,
 1,
 4,
 2,
 0,
 0,
 2,
 1,
 5,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 0,
 5,
 2,
 3,
 2,
 2,
 4,
 1,
 5,
 2,
 0,
 1,
 2,
 4,
 0,
 1,
 2,
 2,
 0,
 0,
 4,
 1,
 0,
 1,
 2,
 5,
 3,
 1,
 1,
 5,
 0,
 1,
 1,
 1,
 2,
 4,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 3,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 0,
 3,
 1,
 1,
 2,
 4,
 1,
 2,
 4,
 1,
 1,
 2,
 1,


In [ ]:
X_eval = eval_df['text'].tolist()
y_eval = eval_df['label'].tolist()
y_eval

[2,
 5,
 3,
 3,
 1,
 2,
 1,
 2,
 2,
 5,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 5,
 0,
 0,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 2,
 2,
 0,
 0,
 5,
 5,
 2,
 4,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 2,
 1,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 5,
 4,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 5,
 1,
 2,
 0,
 1,
 1,
 0,
 3,
 0,
 5,
 4,
 1,
 2,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 3,
 0,
 0,
 1,
 5,
 1,
 4,
 2,
 3,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 3,
 0,
 5,
 4,
 0,
 1,
 5,
 2,
 0,
 1,
 3,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 5,
 0,
 2,
 2,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 4,
 4,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 1,
 5,
 2,
 0,
 0,
 2,
 2,
 1,
 0,
 1,
 0,
 3,
 2,
 1,
 2,
 4,
 0,
 1,
 0,
 2,
 0,
 3,
 2,
 0,
 1,
 1,
 0,
 0,
 3,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 2,
 0,
 5,
 0,
 0,
 2,
 1,
 5,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 5,
 0,
 2,
 2,
 5,
 1,
 3,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 4,
 2,
 2,
 1,
 2,
 0,
 3,
 0,
 1,
 1,
 3,


In [ ]:
X_test = test_df['text'].tolist()
y_test = test_df['label'].tolist()

In [ ]:
train_encodings = tokenizer(X_train, truncation=True, padding=True)
eval_encodings = tokenizer(X_eval, truncation=True, padding=True)
test_encodings = tokenizer(X_test, truncation=True, padding=True)

#### Creating dataset object

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings), y_train))
eval_dataset = tf.data.Dataset.from_tensor_slices((dict(eval_encodings), y_eval))

In [ ]:
training_args = TFTrainingArguments(
    output_dir = '/results',
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=1e-5,
    logging_dir = '/logs',
    logging_steps=10,
    eval_steps=100,
)

In [ ]:
with training_args.strategy.scope():
  model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=6)

  trainer = TFTrainer(
      model=model,
      args = training_args,
      train_dataset=train_dataset,
      eval_dataset=eval_dataset,
  )
      
  trainer.train()

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertForSequenceClassification: ['vocab_projector', 'vocab_layer_norm', 'activation_13', 'vocab_transform']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier', 'dropout_199', 'classifier']
You should probably TRAIN this model on a down-stream task to be able to use 

ValueError: ignored

In [ ]:
result = trainer.evaluate()
result

In [ ]:
save_directory = '/content/drive/MyDrive/Colab Notebooks/Emotion Recognition/saved_model'
model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

In [ ]:
save_directory = '/content/drive/MyDrive/Colab Notebooks/Emotion Recognition'
tokenizer_fine_tuned = DistilBertTokenizerFast.from_pretrained(save_directory)
model_fine_tuned = TFDistilBertForSequenceClassification.from_pretrained(save_directory)

All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at /content/drive/MyDrive/Colab Notebooks/Emotion Recognition.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [ ]:
test_encodings = tokenizer_fine_tuned(
    X_test,
    truncation=True,
    padding=True,
    return_tensors='tf',
)

In [ ]:
testing_data = tf.data.Dataset.from_tensor_slices((dict(test_encodings), y_test))

In [ ]:
final_pred = model_fine_tuned.predict(testing_data)

5033/5033 [==============================] - 42s 7ms/step


In [ ]:
final_pred

TFSequenceClassifierOutput(loss=None, logits=array([[-3.1348217 , -2.5994966 ,  5.8764405 , -2.7520626 , -0.71631724,
        -2.5962691 ],
       [-0.90785575, -1.5490826 ,  4.478897  , -1.6532805 , -1.9813513 ,
        -3.0482025 ],
       [ 7.3329077 , -2.3837187 , -2.6191406 , -1.6298765 , -1.324411  ,
        -3.793209  ],
       ...,
       [ 7.3205085 , -2.2894356 , -2.6859012 , -1.6326156 , -1.3778843 ,
        -3.7416923 ],
       [ 7.1590047 , -2.3385603 , -2.6057255 , -1.2955115 , -1.3321959 ,
        -3.8623896 ],
       [-2.7543886 ,  7.122596  , -2.874509  , -2.1844254 , -1.5630282 ,
        -2.686338  ]], dtype=float32), hidden_states=None, attentions=None)

In [ ]:
final_prediction = tf.argmax(final_pred.logits, axis=1).numpy()

In [ ]:
y_test = [i - 1 for i in (y_test)]

In [ ]:
np.unique(y_test)

array([0, 1, 2, 3, 4, 5])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

cm = confusion_matrix(final_prediction, y_test)
print(cm)
cr = classification_report(final_prediction, y_test)
print(cr)
                           

[[1286  777  758   21    0  326]
 [   3  689    7    1    0    7]
 [   0    4  574   11    5    2]
 [   1    6   12  257    8    4]
 [   0    0    4    2  211   19]
 [   0    1    0    0    0   37]]
              precision    recall  f1-score   support

           0       1.00      0.41      0.58      3168
           1       0.47      0.97      0.63       707
           2       0.42      0.96      0.59       596
           3       0.88      0.89      0.89       288
           4       0.94      0.89      0.92       236
           5       0.09      0.97      0.17        38

    accuracy                           0.61      5033
   macro avg       0.63      0.85      0.63      5033
weighted avg       0.84      0.61      0.62      5033



In [ ]:
def custom_input():
  resp = input("Enter your text : ")
  resp_token = tokenizer_fine_tuned(resp, truncation=True, return_tensors = 'tf')
  custom_test = tf.data.Dataset.from_tensor_slices((dict(resp_token), [0]))
  preds = model_fine_tuned.predict(custom_test)
  print(preds)
  prediction = tf.argmax(preds.logits, axis=1)
  return prediction

In [ ]:
pred_value = custom_input().numpy()[0]
emotion_set = train_df['label_name'].value_counts().index.tolist()
print('Predicted emotion : ', emotion_set[pred_value])

Enter your text : woahh that car is shining like a star
1/1 [==============================] - 0s 39ms/step
TFSequenceClassifierOutput(loss=None, logits=array([[ 7.3502383, -2.3642507, -2.5799751, -1.641869 , -1.361904 ,
        -3.8089483]], dtype=float32), hidden_states=None, attentions=None)
Predicted emotion :  neutral
